Code cleanup
LazoCoder/Pokemon-Terminal pull request #155
Opened 2018-08-04 03:12 UTC by samosaara

This pull request starts the process of standardization and cleanup towards a more lint-able and pep8 compliant code.

I want to first to focus only on the obvious and the one git hates the most, spacing and lines, and the missing `@staticmethod` annotations, but this is not purely for aesthetics, I really want to clean the house up of all the silly defaults we have laying around so we can add more rigid linting to our CI process.

But I also want to keep the PR's focused in order for more focused discussion and consensus for each part.

2018-08-04 03:18 UTC, sylveon requested changes
See comment I left on commit.

Also for heaven's sake, please see #154, you just released a broken version! https://github.com/LazoCoder/Pokemon-Terminal/blob/master/pokemonterminal/platform/named_event/posix.py#L32

2018-08-12 20:45 UTC, sylveon commented
Pretty sure that won't work, because we're calling __str__ as if it was a static method. Maybe we should add a new method to the interface (something like `def name() -> str`) instead

2018-08-12 21:31 UTC, jimmyorourke commented
This could use a rebase 😅

2019-03-28 04:24 UTC, cclauss commented
Lots of conflicts.

2026-02-25 14:44 UTC, closed without merging